package fr.adaming.awal.entity;
// Generated 29 sept. 2014 16:10:20 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

    private Integer idAddress;
    private String city;
    private String street;
    private String postcode;
    private Set clients = new HashSet(0);
    private Set firms = new HashSet(0);
    private Set repairers = new HashSet(0);

    public Address() {
    }

    public Address(Integer idAddress, String city, String street, String postcode) {
        this.idAddress = idAddress;
        this.city = city;
        this.street = street;
        this.postcode = postcode;
    }

    public Address(String city, String street, String postcode) {
        this.city = city;
        this.street = street;
        this.postcode = postcode;
    }

    public Address(String city, String street, String postcode, Set clients, Set firms, Set repairers) {
        this.city = city;
        this.street = street;
        this.postcode = postcode;
        this.clients = clients;
        this.firms = firms;
        this.repairers = repairers;
    }

    public Integer getIdAddress() {
        return this.idAddress;
    }

    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public Set getClients() {
        return this.clients;
    }

    public void setClients(Set clients) {
        this.clients = clients;
    }

    public Set getFirms() {
        return this.firms;
    }

    public void setFirms(Set firms) {
        this.firms = firms;
    }

    public Set getRepairers() {
        return this.repairers;
    }

    public void setRepairers(Set repairers) {
        this.repairers = repairers;
    }
}
