package fr.adaming.awal.entity;
// Generated 8 oct. 2014 14:22:13 by Hibernate Tools 4.3.1


import fr.adaming.awal.entity.interfaces.IEntity;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements IEntity<Integer> {


     private Integer idAddress;
     private String city;
     private String street;
     private String postcode;
     private Set clients = new HashSet(0);
     private Set repairers = new HashSet(0);
     private Set firms = new HashSet(0);

    public Address() {
    }

    public Address(String city, String street, String postcode, Set clients, Set repairers, Set firms) {
       this.city = city;
       this.street = street;
       this.postcode = postcode;
       this.clients = clients;
       this.repairers = repairers;
       this.firms = firms;
    }
   
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
    public Set getRepairers() {
        return this.repairers;
    }
    
    public void setRepairers(Set repairers) {
        this.repairers = repairers;
    }
    public Set getFirms() {
        return this.firms;
    }
    
    public void setFirms(Set firms) {
        this.firms = firms;
    }

    @Override
    public Integer getId() {
       return idAddress;
    }




}


