package fr.adaming.awal.entity;
// Generated 9 oct. 2014 14:54:37 by Hibernate Tools 4.3.1

import fr.adaming.awal.entity.interfaces.IUser;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements IUser<Integer> {

    private Integer idClient;
    private Address address;
    private Firm firm;
    private User user;
    private String numbercard;
    private Set devices = new HashSet(0);

    public Client() {
    }

    public Client(Address address, User user) {
        this.address = address;
        this.user = user;
    }

    public Client(Address address, Firm firm, User user, String numbercard, Set devices) {
        this.address = address;
        this.firm = firm;
        this.user = user;
        this.numbercard = numbercard;
        this.devices = devices;
    }

    public Integer getIdClient() {
        return this.idClient;
    }

    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }

    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Override
    public Firm getFirm() {
        return this.firm;
    }

    public void setFirm(Firm firm) {
        this.firm = firm;
    }

    @Override
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNumbercard() {
        return this.numbercard;
    }

    public void setNumbercard(String numbercard) {
        this.numbercard = numbercard;
    }

    public Set getDevices() {
        return this.devices;
    }

    public void setDevices(Set devices) {
        this.devices = devices;
    }

    @Override
    public Integer getId() {
        return idClient;
    }

    @Override
    public void setId(Integer id) {
        this.idClient = id;
    }

}
