package fr.adaming.awal.entity;
// Generated 2 oct. 2014 13:35:35 by Hibernate Tools 4.3.1

import fr.adaming.awal.entity.interfaces.IUser;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements IUser, java.io.Serializable {

    private Integer idClient;
    private Address address;
    private User user;
    private String numbercard;
    private Set devices = new HashSet(0);

    public Client() {
    }

    public Client(User user) {
        this.user = user;
    }

    public Client(Address address, User user, String numbercard, Set devices) {
        this.address = address;
        this.user = user;
        this.numbercard = numbercard;
        this.devices = devices;
    }

    public Integer getIdClient() {
        return this.idClient;
    }

    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }

    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNumbercard() {
        return this.numbercard;
    }

    public void setNumbercard(String numbercard) {
        this.numbercard = numbercard;
    }

    public Set getDevices() {
        return this.devices;
    }

    public void setDevices(Set devices) {
        this.devices = devices;
    }

}
