package fr.adaming.awal.entity;
// Generated 29 sept. 2014 16:10:20 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private User user;
     private Address address;
     private String numbercard;
     private Set devices = new HashSet(0);

    public Client() {
    }

    public Client(User user, Address address, String numbercard, Set devices) {
       this.user = user;
       this.address = address;
       this.numbercard = numbercard;
       this.devices = devices;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getNumbercard() {
        return this.numbercard;
    }
    
    public void setNumbercard(String numbercard) {
        this.numbercard = numbercard;
    }
    public Set getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set devices) {
        this.devices = devices;
    }




}


