package fr.adaming.awal.entity;
// Generated 2 oct. 2014 14:45:54 by Hibernate Tools 4.3.1

/**
 * Competence generated by hbm2java
 */
public class Competence implements java.io.Serializable {

    private Integer idCompetence;
    private Repairer repairer;
    private String type;

    public Competence() {
    }

    public Competence(Repairer repairer, String type) {
        this.repairer = repairer;
        this.type = type;
    }

    public Integer getIdCompetence() {
        return this.idCompetence;
    }

    public void setIdCompetence(Integer idCompetence) {
        this.idCompetence = idCompetence;
    }

    public Repairer getRepairer() {
        return this.repairer;
    }

    public void setRepairer(Repairer repairer) {
        this.repairer = repairer;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
