package fr.adaming.awal.entity;
// Generated 9 oct. 2014 14:54:37 by Hibernate Tools 4.3.1

import fr.adaming.awal.entity.interfaces.IEntity;
import java.util.Date;

/**
 * Devicerepair generated by hbm2java
 */
public class Devicerepair implements IEntity<Integer> {

    private Integer idDeviceRepair;
    private Device device;
    private Modelpackage modelpackage;
    private Repairer repairer;
    private String description;
    private int price;
    private String state;
    private Date dateCreation;
    private Date dateInRepair;
    private Date dateRepair;
    private Date dateClosed;

    public Devicerepair() {
    }

    public Devicerepair(Device device, Modelpackage modelpackage, int price, Date dateCreation) {
        this.device = device;
        this.modelpackage = modelpackage;
        this.price = price;
        this.dateCreation = dateCreation;
    }

    public Devicerepair(Device device, Modelpackage modelpackage, Repairer repairer, String description, int price, String state, Date dateCreation, Date dateInRepair, Date dateRepair, Date dateClosed) {
        this.device = device;
        this.modelpackage = modelpackage;
        this.repairer = repairer;
        this.description = description;
        this.price = price;
        this.state = state;
        this.dateCreation = dateCreation;
        this.dateInRepair = dateInRepair;
        this.dateRepair = dateRepair;
        this.dateClosed = dateClosed;
    }

    public Integer getIdDeviceRepair() {
        return this.idDeviceRepair;
    }

    public void setIdDeviceRepair(Integer idDeviceRepair) {
        this.idDeviceRepair = idDeviceRepair;
    }

    public Device getDevice() {
        return this.device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    public Modelpackage getModelpackage() {
        return this.modelpackage;
    }

    public void setModelpackage(Modelpackage modelpackage) {
        this.modelpackage = modelpackage;
    }

    public Repairer getRepairer() {
        return this.repairer;
    }

    public void setRepairer(Repairer repairer) {
        this.repairer = repairer;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getPrice() {
        return this.price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public Date getDateInRepair() {
        return this.dateInRepair;
    }

    public void setDateInRepair(Date dateInRepair) {
        this.dateInRepair = dateInRepair;
    }

    public Date getDateRepair() {
        return this.dateRepair;
    }

    public void setDateRepair(Date dateRepair) {
        this.dateRepair = dateRepair;
    }

    public Date getDateClosed() {
        return this.dateClosed;
    }

    public void setDateClosed(Date dateClosed) {
        this.dateClosed = dateClosed;
    }

    @Override
    public Integer getId() {
        return idDeviceRepair;
    }

    @Override
    public void setId(Integer id) {
        this.idDeviceRepair = id;
    }

}
