package fr.adaming.awal.entity;
// Generated 6 oct. 2014 15:26:45 by Hibernate Tools 4.3.1


import fr.adaming.awal.entity.interfaces.IEntity;
import java.util.Date;

/**
 * Deviceinsurance generated by hbm2java
 */
public class Deviceinsurance  implements IEntity<Integer> {


     private int idDeviceInsurance;
     private Device device;
     private Deviceinsurancemodel deviceinsurancemodel;
     private Date beginDate;
     private String description;

    public Deviceinsurance() {
    }

	
    public Deviceinsurance(int idDeviceInsurance, Device device, Deviceinsurancemodel deviceinsurancemodel, Date beginDate) {
        this.idDeviceInsurance = idDeviceInsurance;
        this.device = device;
        this.deviceinsurancemodel = deviceinsurancemodel;
        this.beginDate = beginDate;
    }
    public Deviceinsurance(int idDeviceInsurance, Device device, Deviceinsurancemodel deviceinsurancemodel, Date beginDate, String description) {
       this.idDeviceInsurance = idDeviceInsurance;
       this.device = device;
       this.deviceinsurancemodel = deviceinsurancemodel;
       this.beginDate = beginDate;
       this.description = description;
    }
   
    public int getIdDeviceInsurance() {
        return this.idDeviceInsurance;
    }
    
    public void setIdDeviceInsurance(int idDeviceInsurance) {
        this.idDeviceInsurance = idDeviceInsurance;
    }
    public Device getDevice() {
        return this.device;
    }
    
    public void setDevice(Device device) {
        this.device = device;
    }
    public Deviceinsurancemodel getDeviceinsurancemodel() {
        return this.deviceinsurancemodel;
    }
    
    public void setDeviceinsurancemodel(Deviceinsurancemodel deviceinsurancemodel) {
        this.deviceinsurancemodel = deviceinsurancemodel;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public Integer getId() {
        return getIdDeviceInsurance();
    }

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Deviceinsurance other = (Deviceinsurance) obj;
        if (this.idDeviceInsurance != other.idDeviceInsurance) {
            return false;
        }
        return true;
    }
    
}


