package fr.adaming.awal.entity;
// Generated 2 oct. 2014 13:35:35 by Hibernate Tools 4.3.1

/**
 * Deviceinsurancemodel generated by hbm2java
 */
public class Deviceinsurancemodel implements java.io.Serializable {

    private Integer idDeviceinsurancemodel;
    private Modele modele;
    private String name;
    private String description;
    private Integer duration;

    public Deviceinsurancemodel() {
    }

    public Deviceinsurancemodel(Modele modele) {
        this.modele = modele;
    }

    public Deviceinsurancemodel(Modele modele, String name, String description, Integer duration) {
        this.modele = modele;
        this.name = name;
        this.description = description;
        this.duration = duration;
    }

    public Integer getIdDeviceinsurancemodel() {
        return this.idDeviceinsurancemodel;
    }

    public void setIdDeviceinsurancemodel(Integer idDeviceinsurancemodel) {
        this.idDeviceinsurancemodel = idDeviceinsurancemodel;
    }

    public Modele getModele() {
        return this.modele;
    }

    public void setModele(Modele modele) {
        this.modele = modele;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

}
