package fr.adaming.awal.entity;
// Generated 8 oct. 2014 14:22:13 by Hibernate Tools 4.3.1


import fr.adaming.awal.entity.interfaces.IEntity;
import java.util.HashSet;
import java.util.Set;

/**
 * Firm generated by hbm2java
 */
public class Firm  implements IEntity<Integer> {


     private Integer idFirm;
     private Address address;
     private String name;
     private String phone;
     private String logoPath;
     private String cssPath;
     private Set repairers = new HashSet(0);
     private Set resellers = new HashSet(0);

    public Firm() {
    }

	
    public Firm(String name) {
        this.name = name;
    }
    public Firm(Address address, String name, String phone, String logoPath, String cssPath, Set repairers, Set resellers) {
       this.address = address;
       this.name = name;
       this.phone = phone;
       this.logoPath = logoPath;
       this.cssPath = cssPath;
       this.repairers = repairers;
       this.resellers = resellers;
    }
   
    public Integer getIdFirm() {
        return this.idFirm;
    }
    
    public void setIdFirm(Integer idFirm) {
        this.idFirm = idFirm;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getLogoPath() {
        return this.logoPath;
    }
    
    public void setLogoPath(String logoPath) {
        this.logoPath = logoPath;
    }
    public String getCssPath() {
        return this.cssPath;
    }
    
    public void setCssPath(String cssPath) {
        this.cssPath = cssPath;
    }
    public Set getRepairers() {
        return this.repairers;
    }
    
    public void setRepairers(Set repairers) {
        this.repairers = repairers;
    }
    public Set getResellers() {
        return this.resellers;
    }
    
    public void setResellers(Set resellers) {
        this.resellers = resellers;
    }

    @Override
    public Integer getId() {
        return idFirm;
    }




}


