package fr.adaming.awal.entity;
// Generated 2 oct. 2014 12:02:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modele generated by hbm2java
 */
public class Modele  implements java.io.Serializable {


     private Integer idModele;
     private double weigth;
     private String dimension;
     private String brand;
     private String type;
     private String name;
     private Set devices = new HashSet(0);
     private Deviceinsurancemodel deviceinsurancemodel;
     private Set modelpackages = new HashSet(0);

    public Modele() {
    }

	
    public Modele(double weigth, String dimension, String brand, String type, String name) {
        this.weigth = weigth;
        this.dimension = dimension;
        this.brand = brand;
        this.type = type;
        this.name = name;
    }
    public Modele(double weigth, String dimension, String brand, String type, String name, Set devices, Deviceinsurancemodel deviceinsurancemodel, Set modelpackages) {
       this.weigth = weigth;
       this.dimension = dimension;
       this.brand = brand;
       this.type = type;
       this.name = name;
       this.devices = devices;
       this.deviceinsurancemodel = deviceinsurancemodel;
       this.modelpackages = modelpackages;
    }
   
    public Integer getIdModele() {
        return this.idModele;
    }
    
    public void setIdModele(Integer idModele) {
        this.idModele = idModele;
    }
    public double getWeigth() {
        return this.weigth;
    }
    
    public void setWeigth(double weigth) {
        this.weigth = weigth;
    }
    public String getDimension() {
        return this.dimension;
    }
    
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set devices) {
        this.devices = devices;
    }
    public Deviceinsurancemodel getDeviceinsurancemodel() {
        return this.deviceinsurancemodel;
    }
    
    public void setDeviceinsurancemodel(Deviceinsurancemodel deviceinsurancemodel) {
        this.deviceinsurancemodel = deviceinsurancemodel;
    }
    public Set getModelpackages() {
        return this.modelpackages;
    }
    
    public void setModelpackages(Set modelpackages) {
        this.modelpackages = modelpackages;
    }




}


