package fr.adaming.awal.entity;
// Generated 2 oct. 2014 13:35:35 by Hibernate Tools 4.3.1

import fr.adaming.awal.entity.interfaces.IEntity;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Modele generated by hbm2java
 */
public class Modele implements IEntity<Integer> {

    private Integer idModele;
    private double weigth;
    private String dimension;
    private String brand;
    private String type;
    private String name;
    private Set devices = new HashSet(0);
    private Set modelpackages = new HashSet(0);

    public Modele() {
    }

    public Modele(double weigth, String dimension, String brand, String type, String name) {
        this.weigth = weigth;
        this.dimension = dimension;
        this.brand = brand;
        this.type = type;
        this.name = name;
    }

    public Modele(double weigth, String dimension, String brand, String type, String name, Set devices, Set modelpackages) {
        this.weigth = weigth;
        this.dimension = dimension;
        this.brand = brand;
        this.type = type;
        this.name = name;
        this.devices = devices;
        this.modelpackages = modelpackages;
    }

    @Override
    public Integer getId() {
        return this.idModele;
    }

    public Integer getIdModele() {
        return this.idModele;
    }

    public void setIdModele(Integer idModele) {
        this.idModele = idModele;
    }

    public double getWeigth() {
        return this.weigth;
    }

    public void setWeigth(double weigth) {
        this.weigth = weigth;
    }

    public String getDimension() {
        return this.dimension;
    }

    public void setDimension(String dimension) {
        this.dimension = dimension;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getDevices() {
        return this.devices;
    }

    public void setDevices(Set devices) {
        this.devices = devices;
    }

    public Set getModelpackages() {
        return this.modelpackages;
    }

    public void setModelpackages(Set modelpackages) {
        this.modelpackages = modelpackages;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Modele other = (Modele) obj;
        if (!Objects.equals(this.idModele, other.idModele)) {
            return false;
        }
        return true;
    }

}
