package fr.adaming.awal.entity;
// Generated 29 sept. 2014 16:10:20 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Modelpackage generated by hbm2java
 */
public class Modelpackage implements java.io.Serializable {

    private Integer idModelpackage;
    private Modele modele;
    private String name;
    private String description;
    private String price;
    private Set devicerepairs = new HashSet(0);

    public Modelpackage() {
    }

    public Modelpackage(Modele modele, String name, String description, String price, Set devicerepairs) {
        this.modele = modele;
        this.name = name;
        this.description = description;
        this.price = price;
        this.devicerepairs = devicerepairs;
    }

    public Integer getIdModelpackage() {
        return this.idModelpackage;
    }

    public void setIdModelpackage(Integer idModelpackage) {
        this.idModelpackage = idModelpackage;
    }

    public Modele getModele() {
        return this.modele;
    }

    public void setModele(Modele modele) {
        this.modele = modele;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Set getDevicerepairs() {
        return this.devicerepairs;
    }

    public void setDevicerepairs(Set devicerepairs) {
        this.devicerepairs = devicerepairs;
    }
}
