package fr.adaming.awal.entity;
// Generated 8 oct. 2014 14:22:13 by Hibernate Tools 4.3.1


import fr.adaming.awal.entity.interfaces.IEntity;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Modelpackage generated by hbm2java
 */
public class Modelpackage  implements IEntity<Integer> {


     private Integer idModelpackage;
     private Modele modele;
     private String name;
     private String description;
     private String price;
     private Set devicerepairs = new HashSet(0);

    public Modelpackage() {
    }

	
    public Modelpackage(Modele modele, String name, String price) {
        this.modele = modele;
        this.name = name;
        this.price = price;
    }
    public Modelpackage(Modele modele, String name, String description, String price, Set devicerepairs) {
       this.modele = modele;
       this.name = name;
       this.description = description;
       this.price = price;
       this.devicerepairs = devicerepairs;
    }
   
    public Integer getIdModelpackage() {
        return this.idModelpackage;
    }
    
    public void setIdModelpackage(Integer idModelpackage) {
        this.idModelpackage = idModelpackage;
    }
    public Modele getModele() {
        return this.modele;
    }
    
    public void setModele(Modele modele) {
        this.modele = modele;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public Set getDevicerepairs() {
        return this.devicerepairs;
    }
    
    public void setDevicerepairs(Set devicerepairs) {
        this.devicerepairs = devicerepairs;
    }

    @Override
    public Integer getId() {
        return idModelpackage;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Modelpackage other = (Modelpackage) obj;
        if (!Objects.equals(this.idModelpackage, other.idModelpackage)) {
            return false;
        }
        return true;
    }




}


