package fr.adaming.awal.entity;
// Generated 9 oct. 2014 14:54:37 by Hibernate Tools 4.3.1

import fr.adaming.awal.entity.interfaces.IUser;

/**
 * Reseller generated by hbm2java
 */
public class Reseller implements IUser<Integer> {

    private Integer idSeller;
    private Firm firm;
    private User user;

    public Reseller() {
    }

    public Reseller(User user) {
        this.user = user;
    }

    public Reseller(Firm firm, User user) {
        this.firm = firm;
        this.user = user;
    }

    public Integer getIdSeller() {
        return this.idSeller;
    }

    public void setIdSeller(Integer idSeller) {
        this.idSeller = idSeller;
    }

    @Override
    public Firm getFirm() {
        return this.firm;
    }

    public void setFirm(Firm firm) {
        this.firm = firm;
    }

    @Override
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public Integer getId() {
        return idSeller;
    }

    @Override
    public void setId(Integer id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
