package fr.adaming.awal.entity;
// Generated 2 oct. 2014 13:35:35 by Hibernate Tools 4.3.1



/**
 * Reseller generated by hbm2java
 */
public class Reseller  implements java.io.Serializable {


     private Integer idSeller;
     private Firm firm;
     private User user;

    public Reseller() {
    }

	
    public Reseller(User user) {
        this.user = user;
    }
    public Reseller(Firm firm, User user) {
       this.firm = firm;
       this.user = user;
    }
   
    public Integer getIdSeller() {
        return this.idSeller;
    }
    
    public void setIdSeller(Integer idSeller) {
        this.idSeller = idSeller;
    }
    public Firm getFirm() {
        return this.firm;
    }
    
    public void setFirm(Firm firm) {
        this.firm = firm;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


